from djitellopy import Tello

tello = Tello()

tello.connect()
tello.takeoff()
print("0")
tello.rotate_clockwise(45)
print("1")
tello.move_forward(50)
print("2")
tello.rotate_counter_clockwise(90)
print("3")
tello.move_forward(50)
print("4")
tello.rotate_clockwise(90)
print("5")
tello.move_forward(50)
print("6")
tello.rotate_counter_clockwise(90)
print("7")
tello.move_forward(50)
print("8")
tello.rotate_clockwise(135)
print("9")
tello.move_forward(50)
print("10")
tello.rotate_clockwise(135)
print("11")
tello.move_forward(50)
print("12")
tello.rotate_counter_clockwise(90)
print("13")
tello.move_forward(50)
print("14")
tello.rotate_clockwise(90)
print("15")
tello.move_forward(50)
print("16")
tello.rotate_clockwise(135)
print("17")
tello.land()
print("18")